---
---
title: "226305 Netzwerk Nationalmannschaften, 2020"
subtitle: "Netzwerk Nationalmannschaft Deutschland2014"
author: "Luca Gröning, lg058@hdm-stuttgart.de"
date: '`r format(Sys.Date(), "03. Oktober 2020")`'
output: html_notebook
---

## Links zu meinem Projekt  
- [docs.google](https://docs.google.com/spreadsheets/d/1OwQ6AHSsqH7aRtFXfzDSp0lfxKbGqiQdhiOFK6ZTDOM/edit#gid=991427446) 
- [Github](https://github.com/lucgrnng/Netzwerk-Nationalteams)  
- [Codebuch](https://github.com/lucgrnng/Netzwerk-Nationalteams/blob/master/Codebuch.md)    
- [edgelist](https://github.com/lucgrnng/Netzwerk-Nationalteams/blob/master/Sandhu%20WM%20-%20Edgelist%20Deutschland%202014.csv)  
- [nodelist](https://github.com/lucgrnng/Netzwerk-Nationalteams/blob/master/Sandhu%20WM%20-%20Nodelist%20Deutschland%202014.csv)


```{r Netzwerk einlesen, echo=FALSE, message=FALSE, warning=TRUE, paged.print=FALSE}

library(igraph)
# Erstellt das Netzwerk aus unserer Edge- und Nodelists. 

# Einlesen der Edge- und Nodelist
el <- read.csv("https://raw.githubusercontent.com/lucgrnng/Netzwerk-Nationalteams/master/Sandhu%20WM%20-%20Edgelist%20Deutschland%202014.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/lucgrnng/Netzwerk-Nationalteams/master/Sandhu%20WM%20-%20Nodelist%20Deutschland%202014.csv", header=T, as.is=T, sep = ",")

# Matrix erstellen
edgematrix <-as.matrix(el)

# Zusammenführen von Edge- und Nodelist als igraph-Objekt
# 
Deutschland2014 <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=T)

E(Deutschland2014)$arrow.size <- .3
Deutschland2014
```

```{r}
# Visualisierung des Kaders der deutschen Nationalmannschaft 2014 
 
plot (Deutschland2014,
layout=layout_in_circle,
edge.arrow.size=.1,
edge.color="grey",
edge.curved=.2,
asp=.5,
edge.width=E(Deutschland2014)$weight,
vertex.size=3,
vertex.frame.color=NA,
vertex.label.family="Helvetica",
vertex.label.color="red3",
vertex.label.dist=1,
vertex.size=degree(Deutschland2014),
main="Die deutsche Nationalmannschaft 2014"
)

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
