---
title: "226305 Netwerke Sommersemester 2020"
subtitle: "Netzwerk Nationalmannschaft Frankreich 2018"
author: "Patrick Steinle, ps134@hdm-stuttgart.de"
date: '`r format(Sys.Date(), "3. Oktober 2020")`'
output: html_notebook
---

## Links zu meinem Projekt  
- [docs.google](https://docs.google.com/spreadsheets/d/1OwQ6AHSsqH7aRtFXfzDSp0lfxKbGqiQdhiOFK6ZTDOM/edit#gid=0) 
- [Github](https://github.com/lucgrnng/Netzwerk-Nationalteams)  
- [Codebuch](https://github.com/lucgrnng/Netzwerk-Nationalteams/blob/master/Codebuch.md)    
- [edgelist](https://raw.githubusercontent.com/lucgrnng/Netzwerk-Nationalteams/master/Edgelist-Frankreich%202018.csv)  
- [nodelist](https://raw.githubusercontent.com/lucgrnng/Netzwerk-Nationalteams/master/Nodelist%20Frankreich%202018.csv)


```{r Netzwerk einlesen, echo=FALSE, message=FALSE, warning=TRUE, paged.print=FALSE}
library(igraph)
# Erstellt das Netzwerk aus unserer Edge- und Nodelists. 
# Einlesen der Edge- und Nodelist
el <- read.csv("https://raw.githubusercontent.com/lucgrnng/Netzwerk-Nationalteams/master/Edgelist-Frankreich%202018.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/lucgrnng/Netzwerk-Nationalteams/master/Nodelist%20Frankreich%202018.csv", header=T, as.is=T, sep = ",")
# Matrix erstellen
edgematrix <-as.matrix(el)
# Zusammenführen von Edge- und Nodelist als igraph-Objekt
# 
Frankreich2018 <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=T)
E(Frankreich2018)$arrow.size <- .3
Frankreich2018
```


```{r}
# Visualisierung des Kaders der französischen Nationalmannschaft 2018 
 
plot (Frankreich2018,
      layout=layout_in_circle,
      edge.arrow.size=.1,
      edge.color="grey",
      edge.curved=.2,
      asp=.5,
      edge.width=E(Frankreich2018)$weight,
      vertex.size=3,
      vertex.frame.color=NA,
      vertex.label.family="Helvetica",
      vertex.label.color="red3",
      vertex.label.dist=1,
      vertex.size=degree(Frankreich2018),
      main="Die französische Nationalmannschaft 2018")
```